# -*- coding: utf-8 -*-
"""train_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1--jXRn4mKjSZpZcDy7GyVASxUUDJ4eZ6
"""

import pandas as pd
import numpy as np

# Import Dataset
dataFrame = pd.read_excel("maliciousornot.xlsx")
dtaFrame.head()

# Split Data
from sklearn.model_selection import train_test_split

y = dataFrame["Type"].values
x = dataFrame.drop("Type", axis = 1).values

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.33, random_state = 10)

# Scaling
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

# Build Model
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

model.add(Dense(units = 30, activation = "relu"))
model.add(Dense(units = 15, activation = "relu"))
model.add(Dense(units = 15, activation = "relu"))
model.add(Dense(units = 1, activation = "sigmoid"))

# Compile
model.compile(loss = "binary_crossentropy", optimizer = "adam")

# Train Model
model.fit(x = x_train, y = y_train , epochs = 700, validation_data= (x_test, y_test), verbose = 1)